<?php
/**
 * availability.phtml
 * 
 * @since 14.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<!-- Cta Start -->
<section class="section" style="background: url('https://via.placeholder.com/2000X1333//88929f/5a6270C/O https://placeholder.com/')">
    <div class="bg-overlay"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <h4 class="text-light">I Am Available For Freelancer Project.</h4>
                <p class="text-white-50 mx-auto mt-4 para-desc">Obviously I'M Web Designer. Experienced with all stages of the development cycle for dynamic web projects.</p>
                <div class="mt-4">
                    <a href="#contact" class="btn btn-pill btn-outline-light mouse-down">hire me <i class="mdi mdi-chevron-down"></i></a>
                </div>
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->
</section><!--end section-->
<!-- Cta End -->
