<?php
/**
 * contact.phtml
 * 
 * @since 14.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>

<!-- Contact Start -->
<section class="section pb-0" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <div class="section-title">
                    <div class="titles">
                        <h4 class="title text-uppercase">Contact Me</h4>
                        
                    </div>
                    <p class="text-muted mx-auto para-desc mb-0">Obviously I'M Web Designer. Experienced with all stages of the development cycle for dynamic web projects.</p>
                </div>
            </div><!--end col-->
        </div><!--end row-->

        <div class="row">
            <div class="col-md-4 mt-4 pt-2">
                <div class="contact-detail text-center">
                    <div class="icon">
                        <i class="mdi mdi-phone"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase">Phone</h4>
                        <p class="text-muted">Promising development turmoil inclusive education transformative community</p>
                        <a href="tel:+152534-468-854" class="text-custom">+152 534-468-854</a>
                    </div>  
                </div>
            </div><!--end col-->

            <div class="col-md-4 mt-4 pt-2">
                <div class="contact-detail text-center">
                    <div class="icon">
                        <i class="mdi mdi-email"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase">Email</h4>
                        <p class="text-muted">Promising development turmoil inclusive education transformative community</p>
                        <a href="mailto:contact@example.com" class="text-custom">contact@example.com</a>
                    </div>  
                </div>
            </div><!--end col-->

            <div class="col-md-4 mt-4 pt-2">
                <div class="contact-detail text-center">
                    <div class="icon">
                        <i class="mdi mdi-map-marker"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase">Location</h4>
                        <p class="text-muted">C/54 Northwest Freeway, Suite 558, <br>Houston, USA 485</p>
                        <a href="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d6030.418742494061!2d-111.34563870463673!3d26.01036670629853!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses-419!2smx!4v1471908546569" class="video-play-icon text-custom">View on Google map</a>
                    </div>  
                </div>
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->
</section>
<!--end section-->
<section class="section pt-5 mt-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="custom-form mb-sm-30">
                    <div id="message"></div>
                    <form method="post" action="php/contact.php" name="contact-form" id="contact-form">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="row">
                                    <div class="col-lg-12 col-md-6">
                                        <div class="form-group">
                                            <input name="name" id="name" type="text" class="form-control border rounded" placeholder="First Name :">
                                        </div>
                                    </div><!--end col-->
                                    <div class="col-lg-12 col-md-6">
                                        <div class="form-group">
                                            <input name="email" id="email" type="email" class="form-control border rounded" placeholder="Your email :">
                                        </div> 
                                    </div><!--end col-->
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <input name="subject" id="subject" class="form-control border rounded" placeholder="Your subject :">
                                        </div>                                                                               
                                    </div><!--end col-->
                                </div><!--end row-->
                            </div><!--end col-->

                            <div class="col-lg-6">
                                <div class="form-group">
                                    <textarea name="comments" id="comments" rows="4" class="form-control border rounded" placeholder="Your Message :"></textarea>
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                        <div class="row">
                            <div class="col-sm-12 text-right">
                                <input type="submit" id="submit" name="send" class="submitBnt btn btn-pill btn-custom" value="Send Message">
                                <div id="simple-msg"></div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </form><!--end form-->
                </div><!--end custom-form-->
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->
</section><!--end section-->
<!-- Contact End -->