<?php
/**
 * counter.phtml
 * 
 * @since 14.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<!-- Counter Start -->
<section class="section-two" style="background: url('https://via.placeholder.com/2000X1333//88929f/5a6270C/O https://placeholder.com/')">
    <div class="bg-overlay"></div>
    <div class="container">
        <div class="row" id="counter">
            <div class="col-lg-3 col-6">
                <div class="counter-box rounded text-center">
                    <div class="counter-icon">
                        <i class="mdi mdi-emoticon-happy-outline text-custom"></i>
                    </div>
                    <h5 class="counter-head mt-3 text-white">Happy Client</h5>
                    <h2 class="counter-value mb-0 text-white" data-count="1251">95</h2>
                </div><!--end counter box-->
            </div><!--end col-->

            <div class="col-lg-3 col-6">
                <div class="counter-box rounded text-center">
                    <div class="counter-icon">
                        <i class="mdi mdi-trophy-award text-custom"></i>
                    </div>
                    <h5 class="counter-head mt-3 text-white">Award Won</h5>
                    <h2 class="counter-value mb-0 text-white" data-count="15">1</h2>
                </div><!--end counter box-->
            </div><!--end col-->

            <div class="col-lg-3 col-6 mt-4 pt-2 mt-lg-0 pt-lg-0">
                <div class="counter-box rounded text-center">
                    <div class="counter-icon">
                        <i class="mdi mdi-coffee-outline text-custom"></i>
                    </div>
                    <h5 class="counter-head mt-3 text-white">Cup of Coffee</h5>
                    <h2 class="counter-value mb-0 text-white" data-count="3261">30</h2>
                </div><!--end counter box-->
            </div><!--end col-->

            <div class="col-lg-3 col-6 mt-4 pt-2 mt-lg-0 pt-lg-0">
                <div class="counter-box rounded text-center">
                    <div class="counter-icon">
                        <i class="mdi mdi-monitor text-custom"></i>
                    </div>
                    <h5 class="counter-head mt-3 text-white">Project Complete</h5>
                    <h2 class="counter-value mb-0 text-white" data-count="36">3</h2>
                </div><!--end counter box-->
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->
</section><!--end section-->
<!-- Counter End -->