<?php
/**
 * education.phtml
 * 
 * @since 14.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<!-- Resume start -->
<section class="section" id="education">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <div class="section-title">
                    <div class="titles">
                        <h4 class="title text-uppercase"><?= $this->translate('Ausbildung') ?></h4>

                    </div>                    
                </div>
            </div><!--end col-->
        </div><!--end row-->
        <div class="row">
            <div class="col-12">
                <div class="main-icon text-center mt-4 pt-2">
                    <i class="pe-7s-study rounded-pill"></i>
                </div>
                <div class="timeline-page pt-4 position-relative">
                    <div class="timeline-item mb-4">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="duration date-label-left border rounded p-2 pl-4 pr-4 position-relative shadow text-left">04.2002 – 09.2003</div>
                            </div><!--end col-->
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="event event-description-right rounded p-4 border float-left text-left">
                                    <h4 class="title mb-0 text-capitalize"><?= $this->translate('Weiterbildung') ?></h4>
                                    <small class="company"><?= $this->translate('Bildungszentrum für Informationsverarbeitende Berufe') ?></small>
                                    <ul class="timeline-subtitle mt-3 mb-0 text-muted" style="text-align: left">
                                        <li>
                                            <?= $this->translate('Weiterbildung zum Staatlich geprüften Informatiker') ?>.
                                        </li>
                                        <li>
                                            <b><?= $this->translate('Schwerpunkte') ?>:</b> Java, C, C++, PHP, UML, UNIX/ Linux, Windows NT/2000, SQL, Oracle, HTML, CSS, Javascript.
                                        </li>
                                        <li>
                                            <b><?= $this->translate('Abschluss') ?>:</b> <?= $this->translate('Staatlich geprüfter Informatiker, Fachrichtung Softwaretechnologie') ?>.
                                        </li>
                                    </ul>                                                         
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end timeline item-->

                    <div class="timeline-item mb-4">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 order-sm-1 order-2">
                                <div class="event event-description-left rounded p-4 border float-left text-right "> 
                                    <h4 class="title mb-0 text-capitalize"><?= $this->translate('Sprachkurs Deutsch') ?></h4>
                                    <small class="company"><?= $this->translate('Berlitz Sprachschule Wuppertal') ?></small> 
                                    <ul class="timeline-subtitle mt-3 mb-0 text-muted" style="text-align: left">
                                        <li>
                                            <?= $this->translate('Übersiedlung nach Deutschland und Integrationsphase mit Sprachkurs Deutsch') ?>
                                        </li>
                                    </ul>
                                </div>

                            </div><!--end col-->
                            <div class="col-lg-6 col-md-6 col-sm-6 order-sm-2 order-1">
                                <div class="duration duration-right rounded border p-2 pl-4 pr-4 position-relative shadow text-left">09.2000 - 03.2002</div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end timeline item-->


                    <div class="timeline-item mb-4">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="duration date-label-left border rounded p-2 pl-4 pr-4 position-relative shadow text-left">04.2002 – 09.2003</div>
                            </div><!--end col-->
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="event event-description-right rounded p-4 border float-left text-left">
                                    <h4 class="title mb-0 text-capitalize"><?= $this->translate('Studium') ?></h4>
                                    <small class="company"><?= $this->translate('Radiotechnische Fachhochschule Minsk') ?></small>
                                    <ul class="timeline-subtitle mt-3 mb-0 text-muted" style="text-align: left">
                                        <li>
                                            <?= $this->translate('Studium der Ingenieur-Elektrik') ?>.
                                        </li>
                                        <li>
                                            <b><?= $this->translate('Schwerpunkte') ?>:</b> <?= $this->translate('Produktionsautomatisierung, Automatik und Telemecanique, Produktionsroboter') ?>.
                                        </li>
                                        <li>
                                            <b><?= $this->translate('Abschluss') ?>:</b> <?= $this->translate('Diplom-Ingenieur (FH/BY)') ?>.
                                        </li>
                                    </ul>                                                         
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end timeline item-->
                </div><!--end timeline page-->
                <!-- TIMELINE END -->
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->   
</section><!--end section-->
<!-- Resume End -->