<?php
/**
 * hobby.phtml
 * 
 * @since 15.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<!-- Hobbys start -->
<section class="section" id="hobbys">
    <div class="container">       
        <div class="row">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 text-center">
                        <div class="section-title">
                            <div class="titles">
                                <h4 class="title text-uppercase"><?= $this->translate('Hobbys &amp; Interessen') ?></h4>
                                
                            </div>
                            <p class="text-muted mx-auto para-desc mb-0"><?= $this->translate('Programmierer sind auch nur Menschen') ?>.</p>
                        </div>
                    </div><!--end col-->
                </div><!--end row-->

                <div class="row">
                    <div class="col-lg-3 col-md-4 col-12 mt-4 pt-2">
                        <div class="interests-desc bg-light position-relative p-2 rounded">
                            <div class="hobbies d-flex">
                                <div class="icon text-center rounded-pill mr-4">
                                    <i class="mdi mdi-24px mdi-responsive"></i>
                                </div>
                                <div class="content mt-2">
                                    <h4 class="title mb-0"><?= $this->translate('Programmierung') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->

                    <div class="col-lg-3 col-md-4 col-12 mt-4 pt-2">
                        <div class="interests-desc bg-light position-relative p-2 rounded">
                            <div class="hobbies d-flex">
                                <div class="icon text-center rounded-pill mr-4">
                                    <i class="mdi mdi-24px mdi-video"></i>
                                </div>
                                <div class="content mt-2">
                                    <h4 class="title mb-0"><?= $this->translate('Kino') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->

                    <div class="col-lg-3 col-md-4 col-12 mt-4 pt-2">
                        <div class="interests-desc bg-light position-relative p-2 rounded">
                            <div class="hobbies d-flex">
                                <div class="icon text-center rounded-pill mr-4">
                                    <i class="mdi mdi-24px mdi-coffee"></i>
                                </div>
                                <div class="content mt-2">
                                    <h4 class="title mb-0"><?= $this->translate('Kaffee') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->
                    <div class="col-lg-3 col-md-4 col-12 mt-4 pt-2">
                        <div class="interests-desc bg-light position-relative p-2 rounded">
                            <div class="hobbies d-flex">
                                <div class="icon text-center rounded-pill mr-4">
                                    <i class="mdi mdi-24px mdi-bike"></i>
                                </div>
                                <div class="content mt-2">
                                    <h4 class="title mb-0"><?= $this->translate('Sports') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->

                    <div class="col-lg-3 col-md-4 col-12 mt-4 pt-2">
                        <div class="interests-desc bg-light position-relative p-2 rounded">
                            <div class="hobbies d-flex">
                                <div class="icon text-center rounded-pill mr-4">
                                    <i class="mdi mdi-24px mdi-history"></i>
                                </div>
                                <div class="content mt-2">
                                    <h4 class="title mb-0"><?= $this->translate('Geschichte') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div><!--end col--> 
                    <div class="col-lg-3 col-md-4 col-12 mt-4 pt-2">
                        <div class="interests-desc bg-light position-relative p-2 rounded">
                            <div class="hobbies d-flex">
                                <div class="icon text-center rounded-pill mr-4">
                                    <i class="mdi mdi-24px mdi-cat"></i>
                                </div>
                                <div class="content mt-2">
                                    <h4 class="title mb-0"><?= $this->translate('Haustiere') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->   
                    <div class="col-lg-3 col-md-4 col-12 mt-4 pt-2">
                        <div class="interests-desc bg-light position-relative p-2 rounded">
                            <div class="hobbies d-flex">
                                <div class="icon text-center rounded-pill mr-4">
                                    <i class="mdi mdi-24px mdi-emoticon-devil"></i>
                                    <!--<i class="mdi mdi-24px mdi-sword-cross"></i>-->
                                </div>
                                <div class="content mt-2">
                                    <h4 class="title mb-0"><?= $this->translate('Politik') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->       
                    <div class="col-lg-3 col-md-4 col-12 mt-4 pt-2">
                        <div class="interests-desc bg-light position-relative p-2 rounded">
                            <div class="hobbies d-flex">
                                <div class="icon text-center rounded-pill mr-4">
                                    <i class="mdi mdi-24px mdi-book-open"></i>
                                </div>
                                <div class="content mt-2">
                                    <h4 class="title mb-0"><?= $this->translate('Literatur') ?></h4>
                                </div>
                            </div>
                        </div>
                    </div><!--end col-->
                </div>
            </div><!--end container-->
        </div><!--end row-->
    </div><!--end container-->   
</section><!--end section-->
<!-- Hobbys End -->