<?php
/**
 * resume.phtml
 * 
 * @since 14.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<!-- Resume start -->
<section class="section" id="resume">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <div class="section-title">
                    <div class="titles">
                        <h4 class="title text-uppercase"><?= $this->translate('Berufserfahrung') ?></h4>
                        
                    </div>
                    <p class="text-muted mx-auto para-desc mb-0"><q><?= $this->translate('Chef, schnell oder gut') ?>?</q></p>
                </div>
            </div><!--end col-->
        </div><!--end row-->
        <div class="row">
            <div class="col-12">
                <div class="main-icon text-center mt-4 pt-2">
                    <i class="pe-7s-tools rounded-pill"></i>
                </div>
                <div class="timeline-page pt-4 position-relative">
                    <div class="timeline-item mb-4">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="duration date-label-left border rounded p-2 pl-4 pr-4 position-relative shadow text-left"><?= $this->translate('Seit') ?> 11.2018</div>
                            </div><!--end col-->
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="event event-description-right rounded p-4 border float-left text-left">
                                    <h4 class="title mb-0 text-capitalize"><?= $this->translate('Familienphase') ?></h4>
<!--                                    <small class="company">Vivo - Senior Designer</small>
                                    <p class="timeline-subtitle mt-3 mb-0 text-muted">Familienphase</p>-->
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end timeline item-->

                    <div class="timeline-item mb-4">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 order-sm-1 order-2">
                                <div class="event event-description-left rounded p-4 border float-left text-right">
                                    <h4 class="title mb-0 text-capitalize"><?= $this->translate('Softwareentwickler') ?></h4>
                                    <small class="company">SYSTHAM Data Consulting GmbH & Co. KG</small>
                                    <ul class="timeline-subtitle mt-3 mb-0 text-muted" style="text-align: left">
                                        <li>
                                            <?= $this->translate('Softwarearchitektur, Design und Konzeption eines PIM (Product Information Management) mit MAM/DAM (Media/Data Asset Management) und mehreren APIs') ?>
                                        </li>
                                        <li>
                                            <?= $this->translate('Datenbankdesign und -tuning') ?>
                                        </li>
                                        <li>
                                            PHP (Zend Framework 2/ 3), Java (Maven, Hibernate), MySQL, Elasticsearch 5.*, Java-Script (JQuery), HTML 5, CSS 3
                                        </li>
                                    </ul>                                    
                                </div>
                            </div><!--end col-->
                            <div class="col-lg-6 col-md-6 col-sm-6 order-sm-2 order-1">
                                <div class="duration duration-right rounded border p-2 pl-4 pr-4 position-relative shadow text-left">01.2012 – 10.2018</div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end timeline item-->

                    <div class="timeline-item mb-4">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="duration date-label-left border rounded p-2 pl-4 pr-4 position-relative shadow text-left">01.2011 – 06.2011</div>
                            </div><!--end col-->
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="event event-description-right rounded p-4 border float-left text-left">
                                    <h4 class="title mb-0 text-capitalize"><?= $this->translate('Softwareentwickler') ?></h4>
                                    <small class="company">Edouard Khaikin – Software Engineering</small>
                                    <ul class="timeline-subtitle mt-3 mb-0 text-muted" style="text-align: left">
                                        <li>
                                            <?= $this->translate('Softwarearchitektur, Design und Konzeption von WEB-Anwendungen') ?>
                                        </li>
                                        <li>
                                            <?= $this->translate('Einsatz von OOP zur schnelleren Programmierung von WEB-Seiten') ?>
                                        </li>
                                        <li>
                                            PHP/ Zend Framework, HTML/ XHTML, CSS, Javascript/ JQuery, MySQL, SQLite
                                        </li>
                                    </ul>          
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end timeline item-->

                    <div class="timeline-item mb-4">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 order-sm-1 order-4">
                                <div class="event event-description-left rounded p-4 border float-left text-right">
                                    <h4 class="title mb-0 text-capitalize"><?= $this->translate('Softwareentwickler') ?></h4>
                                    <small class="company">wap3 Technologies GmbH</small>
                                    <ul class="timeline-subtitle mt-3 mb-0 text-muted" style="text-align: left">
                                        <li>
                                            <?= $this->translate('Analyse, Design und Konzeption verteilter Anwendungen (Webentwicklung/ Mobile Applikationen)') ?>
                                        </li>
                                        <li>
                                            <?= $this->translate('Datenbankdesign und -Tuning') ?> 
                                        </li>
                                        <li>
                                            PHP, Java, OOA, OOD, UML, MySQL, PostgreSQL, Java-Script, XHTML, WML, CSS, FreeBSD, Eclipse
                                        </li>
                                    </ul>                                    
                                </div>
                            </div><!--end col-->
                            <div class="col-lg-6 col-md-6 col-sm-6 order-sm-2 order-1">
                                <div class="duration duration-right rounded border p-2 pl-4 pr-4 position-relative shadow text-left">12.2003 – 09.2009</div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end timeline item-->

                    <div class="timeline-item mb-4">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="duration date-label-left border rounded p-2 pl-4 pr-4 position-relative shadow text-left">01.2011–06.2011</div>
                            </div><!--end col-->
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="event event-description-right rounded p-4 border float-left text-left">
                                    <h4 class="title mb-0 text-capitalize"><?= $this->translate('Datenbankentwickler') ?></h4>
                                    <small class="company"><?= $this->translate('Evangelischer Fachverband Schuldnerberatung') ?></small>
                                    <ul class="timeline-subtitle mt-3 mb-0 text-muted" style="text-align: left">
                                        <li>
                                            <?= $this->translate('Access-Datenbank Tuning') ?>
                                        </li>                                        
                                    </ul>          
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end timeline item-->
                </div><!--end timeline page-->
                <!-- TIMELINE END -->
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->
</section><!--end section-->
<!-- Resume End -->