<?php
/**
 * services.phtml
 * 
 * @since 14.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<!-- Services Start -->
<section class="section" id="services">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <div class="section-title">
                    <div class="titles">
                        <h4 class="title text-uppercase"><?= $this->translate('Kompetenz') ?></h4>
                        
                    </div>
                    <p class="text-muted mx-auto para-desc mb-0"><?= $this->translate('#service competence') ?>.</p>
                </div>
            </div><!--end col-->
        </div><!--end row-->
    
        <div class="row row-eq-height">                    
            <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
                <div class="service-wrapper rounded position-relative text-center border p-4 pt-5 pb-5">
                    <div class="icon text-custom">
                        <i class="mdi mdi-language-php text-custom"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase">PHP</h4>
                        <p class="text-muted mt-3 mb-0"><?= $this->translate('#service php') ?>.
                        HTML, CSS, Javascript, JQuery <?= $this->translate('gehören dazu') ?>.
                        </p>
                    </div>
                </div>
            </div><!--end col-->

            <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
                <div class="service-wrapper rounded position-relative text-center border p-4 pt-5 pb-5">
                    <div class="icon text-custom">
                        <i class="mdi mdi-language-java text-custom"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase">Java</h4>
                        <p class="text-muted mt-3 mb-0"><?= $this->translate('#service java') ?>.</p>
                    </div>
                </div>
            </div><!--end col-->

            <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
                <div class="service-wrapper rounded position-relative text-center border p-4 pt-5 pb-5">
                    <div class="icon text-custom">
                        <i class="mdi mdi-database text-custom"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase">SQL</h4>
                        <p class="text-muted mt-3 mb-0"><?= $this->translate('#service sql') ?>.</p>
                    </div>
                </div>
            </div><!--end col-->

            <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
                <div class="service-wrapper rounded position-relative text-center border p-4 pt-5 pb-5">
                    <div class="icon text-custom">
                        <i class="mdi mdi-view-module text-custom"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase">OOP</h4>
                        <p class="text-muted mt-3 mb-0"><?= $this->translate('#service oop') ?>.</p>
                    </div>
                </div>
            </div><!--end col-->

            <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
                <div class="service-wrapper rounded position-relative text-center border p-4 pt-5 pb-5">
                    <div class="icon text-custom">
                        <i class="mdi mdi-security text-custom"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase"><?= $this->translate('Web Security') ?></h4>
                        <p class="text-muted mt-3 mb-0"><?= $this->translate('#service security') ?>.</p>
                    </div>
                </div>
            </div><!--end col-->

            <div class="col-lg-4 col-md-6 col-12 mt-4 pt-2">
                <div class="service-wrapper rounded position-relative text-center border p-4 pt-5 pb-5">
                    <div class="icon text-custom">
                        <i class="mdi mdi-code-tags text-custom"></i>
                    </div>
                    <div class="content mt-3">
                        <h4 class="title text-uppercase"><?= $this->translate('Code') ?></h4>
                        <p class="text-muted mt-3 mb-0"><?= $this->translate('#service code') ?>.</p>
                    </div>
                </div>
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->
</section><!--end section-->
<!-- Services End -->