<?php
/**
 * expertise.phtml
 * 
 * @since 14.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
?>
<!-- Skill & CTA START -->
<section class="section cta-full">
    <div class="container-fluid">
        <div class="row position-relative">
            <div class="col-lg-4 padding-less img" style="background-image:url('https://via.placeholder.com/1100X1333//88929f/5a6270C/O https://placeholder.com/')" data-jarallax='{"speed": 0.5}'></div><!-- end col -->
            <div class="col-lg-8 offset-lg-4">
                <div class="cta-full-img-box">
                    <div class="row justify-content-center">
                        <div class="col-12 text-center">
                            <div class="section-title">
                                <div class="titles">
                                    <h4 class="title text-uppercase">Work Expertise</h4>
                                    
                                </div>
                                <p class="text-muted mx-auto para-desc mb-0">Obviously I'M Web Designer. Experienced with all stages of the development cycle for dynamic web projects.</p>
                            </div>
                        </div><!--end col-->
                    </div><!--end row-->

                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-4 col-12">
                            <ul class="nav nav-pills flex-column" id="pills-tab" role="tablist">
                                <li class="nav-item mt-4 pt-2">
                                    <a class="nav-link active" id="pills-cloud-tab" data-toggle="pill" href="#pills-cloud" role="tab" aria-controls="pills-cloud" aria-selected="false">
                                        <div class="skill-container text-center pt-1 pb-1">
                                            <h4 class="title font-weight-normal mb-0">UX Design</h4>
                                        </div>
                                    </a><!--end nav link-->
                                </li><!--end nav item-->

                                <li class="nav-item mt-4 pt-2">
                                    <a class="nav-link" id="pills-smart-tab" data-toggle="pill" href="#pills-smart" role="tab" aria-controls="pills-smart" aria-selected="false">
                                        <div class="skill-container text-center pt-1 pb-1">
                                            <h4 class="title font-weight-normal mb-0">Languages</h4>
                                        </div>
                                    </a><!--end nav link-->
                                </li><!--end nav item-->

                                <li class="nav-item mt-4 pt-2">
                                    <a class="nav-link" id="pills-apps-tab" data-toggle="pill" href="#pills-apps" role="tab" aria-controls="pills-apps" aria-selected="false">
                                        <div class="skill-container text-center pt-1 pb-1">
                                            <h4 class="title font-weight-normal mb-0">Development</h4>
                                        </div>
                                    </a><!--end nav link-->
                                </li><!--end nav item-->
                            </ul><!--end nav pills-->
                        </div><!--end col-->

                        <div class="col-lg-9 col-md-8 col-12">
                            <div class="tab-content pl-lg-4" id="pills-tabContent">
                                <div class="tab-pane fade show active" id="pills-cloud" role="tabpanel" aria-labelledby="pills-cloud-tab">
                                    <div class="progress-box mt-4 pt-2">
                                        <h6 class="title text-muted">HTML</h6>
                                        <div class="progress">
                                            <div class="progress-bar position-relative bg-custom" style="width:84%;">
                                                <div class="progress-value d-block text-muted h6">84%</div>
                                            </div>
                                        </div>
                                    </div><!--end process box-->
                                    <div class="progress-box mt-4 pt-2">
                                        <h6 class="title text-muted">CSS</h6>
                                        <div class="progress">
                                            <div class="progress-bar position-relative bg-custom" style="width:75%;">
                                                <div class="progress-value d-block text-muted h6">75%</div>
                                            </div>
                                        </div>
                                    </div><!--end process box-->
                                    <div class="progress-box mt-4 pt-2">
                                        <h6 class="title text-muted">JQuery</h6>
                                        <div class="progress">
                                            <div class="progress-bar position-relative bg-custom" style="width:79%;">
                                                <div class="progress-value d-block text-muted h6">79%</div>
                                            </div>
                                        </div>
                                    </div><!--end process box-->
                                </div><!--end teb pane-->

                                <div class="tab-pane fade" id="pills-smart" role="tabpanel" aria-labelledby="pills-smart-tab">
                                    <div class="progress-box mt-4 pt-2">
                                        <h6 class="title text-muted">English</h6>
                                        <div class="progress">
                                            <div class="progress-bar position-relative bg-custom" style="width:84%;">
                                                <div class="progress-value d-block text-muted h6">84%</div>
                                            </div>
                                        </div>
                                    </div><!--end process box-->
                                    <div class="progress-box mt-4 pt-2">
                                        <h6 class="title text-muted">Spanish</h6>
                                        <div class="progress">
                                            <div class="progress-bar position-relative bg-custom" style="width:75%;">
                                                <div class="progress-value d-block text-muted h6">75%</div>
                                            </div>
                                        </div>
                                    </div><!--end process box-->
                                    <div class="progress-box mt-4 pt-2">
                                        <h6 class="title text-muted">German</h6>
                                        <div class="progress">
                                            <div class="progress-bar position-relative bg-custom" style="width:79%;">
                                                <div class="progress-value d-block text-muted h6">79%</div>
                                            </div>
                                        </div>
                                    </div><!--end process box-->
                                </div><!--end teb pane-->

                                <div class="tab-pane fade" id="pills-apps" role="tabpanel" aria-labelledby="pills-apps-tab">
                                    <div class="progress-box mt-4 pt-2">
                                        <h6 class="title text-muted">Photoshop</h6>
                                        <div class="progress">
                                            <div class="progress-bar position-relative bg-custom" style="width:84%;">
                                                <div class="progress-value d-block text-muted h6">84%</div>
                                            </div>
                                        </div>
                                    </div><!--end process box-->
                                    <div class="progress-box mt-4 pt-2">
                                        <h6 class="title text-muted">Sketch</h6>
                                        <div class="progress">
                                            <div class="progress-bar position-relative bg-custom" style="width:75%;">
                                                <div class="progress-value d-block text-muted h6">75%</div>
                                            </div>
                                        </div>
                                    </div>
                                </div><!--end teb pane-->
                            </div><!--end tab content-->
                        </div><!--end col-->
                    </div> <!-- end row --> 
                </div> <!-- end about detail -->
            </div> <!-- end col -->        
        </div><!--end row-->
    </div><!--end container fluid-->
</section><!--end section-->   
<!-- Skill & CTA End -->