<?php
/**
 * layout.phtml
 * 
 * @since 14.04.2020
 * @author Alexej Kisselev <alexej.kisselev@gmail.com>
 */
/* array locale => name*/
$availableLanguages = $this->getServiceManager()->get('Config')['translator']['available'];
/* current language like de, en etc. */
$currentLanguage = substr($this->getServiceManager()->get('translator')->getLocale(), 0, 2);
?>

<!DOCTYPE html>
<html lang="<?= $currentLanguage ?>">
    <head>
        <meta charset="utf-8" />
        <title><?= $this->translate('Alexej Kisselev') ?> - <?= $this->translate('Homepage') ?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Responsive Personal Template" />
        <meta name="keywords" content="<?= $this->translate('Alexej Kisselev') ?>, <?= $this->translate('Softwareentwickler') ?>, <?= $this->translate('Programmierer') ?>, PHP, Java, Zend Framework, Laminas, Doctrine, Maven, Hibernate" />
        <meta name="author" content="<?= $this->translate('Alexej Kisselev') ?>" />
        <meta name="E-mail" content="alexej.kisselev@gmail.com" />
        <meta name="Website" content="kisselev.de" />
        <!-- favicon -->
        <link rel="shortcut icon" href="images/favicon.ico">
        <!-- Bootstrap, Magnific, Icons -->        
        <link href="/css/assets.css" rel="stylesheet" type="text/css" />          
        <!-- Custom Css -->
        <link href="/css/style.css" rel="stylesheet" type="text/css" />
        <link href="/css/colors/orange.css" rel="stylesheet" id="color-opt">
        <link href="/css/custom.css" rel="stylesheet" type="text/css" />
    </head>

    <body>
        <!-- Loader Start -->
        <div id="preloader">
            <div id="status">
                <div class="spinner">
                    <div class="dot1"></div>
                    <div class="dot2"></div>
                </div>
            </div>
        </div>
        <!-- Loader End -->

        <!-- Navbar Start -->
        <nav class="navbar navbar-expand-lg fixed-top navbar-custom navbar-light sticky">
            <div class="container">
<!--                <a class="navbar-brand" href="#">
                    <img src="images/sign.png" height="15" alt="">
                </a>-->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="mdi mdi-menu"></span>
                </button><!--end button-->

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav navbar-nav-link mx-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#home"><?= $this->translate('Home') ?></a>
                        </li><!--end nav item-->
                        <li class="nav-item">
                            <a class="nav-link" href="#about"><?= $this->translate('Über mich') ?></a>
                        </li><!--end nav item-->  
                        <li class="nav-item">
                            <a class="nav-link" href="#services"><?= $this->translate('Kompetenz') ?></a>
                        </li><!--end nav item-->
                        <li class="nav-item">
                            <a class="nav-link" href="#resume"><?= $this->translate('Berufserfahrung') ?></a>
                        </li><!--end nav item-->
                        <li class="nav-item">
                            <a class="nav-link" href="#education"><?= $this->translate('Ausbildung') ?></a>
                        </li><!--end nav item--> 
                    </ul>

                    <?php
                    if (is_array($availableLanguages) && count($availableLanguages) > 0):                        
                        $icon = $currentLanguage !== 'en' ? $currentLanguage : 'uk';
                        ?>
                        <div class="dropdown mb-0 mt-2 mt-sm-0">
                            <a class="btn btn-sm dropdown-toggle" href="#" role="button" id="dropdownLanguageSwitch" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="<?= $icon ?> flag"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownLanguageSwitch">
                                <?php
                                foreach($availableLanguages as $key => $value):
                                    $language = substr($key, 0, 2);
                                    if ($language === $currentLanguage) {
                                        continue;
                                    }
                                    $icon = $language !== 'en' ? $language : 'uk';
                                    ?>
                                    <a class="dropdown-item" href="<?= $this->url('home', ['language' => $language]); ?>">
                                        <i class="<?= $icon ?> flag"></i> <?= $this->translate($value) ?>
                                    </a>
                                <?php endforeach; ?>   
                            </div>
                        </div> 
                    <?php endif; ?>

                    <ul class="list-unstyled mb-0 mt-2 mt-sm-0 social-icon">
                        <li class="list-inline-item"><a href="https://www.xing.com/profile/Alexej_Kisselev/cv" target="_blank" title="XING"><i class="mdi mdi-xing"></i></a></li>                        
                    </ul>
                </div> 
            </div><!--end container-->
        </nav><!--end navbar-->
        <!-- Navbar End -->

        <?= $this->content ?>

        <!-- Footer Start -->
        <footer class="footer bg-dark">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 text-center">
                        <!--                        <a href="#">
                                                    <img src="images/logo-light.png" height="20" alt="">
                                                </a>-->
                        <h4 class="title text-center mb-3"><?= $this->translate('Alexej Kisselev') ?></h4>
                        <p class="para-desc mx-auto mt-4"><?= $this->translate('Softwareentwickler') ?></p>
                        <ul class="list-unstyled mb-0 mt-4 social-icon">
                            <li class="list-inline-item"><a href="https://www.xing.com/profile/Alexej_Kisselev/cv" target="_blank" title="XING"><i class="mdi mdi-xing"></i></a></li>
                        </ul>
                    </div><!--end col-->
                </div><!--end row-->
            </div><!--end container-->
        </footer><!--end footer-->
        <footer class="footer footer-bar bg-dark">
            <div class="container text-foot text-center">
                <p class="mb-0">2008 - <?php echo date("Y"); ?> &copy; <?= $this->translate('Alexej Kisselev') ?> - <?= $this->translate('Softwareentwickler') ?>. Design with <i class="mdi mdi-heart text-danger"></i> by <a href="http://www.shreethemes.in/" target="_blank" class="text-white">Shreethemes</a>.</p>
            </div><!--end container-->
        </footer><!--end footer-->
        <!-- Footer End -->

        <!-- Back to top -->
        <a href="#" class="back-to-top rounded text-center" id="back-to-top"> 
            <i class="mdi mdi-chevron-up d-block"> </i> 
        </a>
        <!-- Back to top -->

        <!-- javascript -->
         <!--<script src="js/particles.js"></script>-->  
        <!--<script src="js/particles.app.js"></script>-->
        <!-- Main Js -->
        <script src="/js/assets.js"></script>-->
        <script src="/js/app.js"></script>
        <!--        <link href="/plugins/prt/style.css" rel="stylesheet" type="text/css" />
                <script src="/plugins/prt/script.js"></script>-->

<!--                <link href="/plugins/looking-for-everything/style.css" rel="stylesheet" type="text/css" />
                <script src="/plugins/looking-for-everything/script.js"></script>-->
    </body>

</html>