<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
echo $this->render('application/partial/section/home');
echo $this->render('application/partial/section/about');
echo $this->render('application/partial/section/services');
//echo $this->render('application/partial/section/counter');
echo $this->render('application/partial/section/resume');
//echo $this->render('application/partial/section/skill');
echo $this->render('application/partial/section/education');
echo $this->render('application/partial/section/hobbys');
//echo $this->render('application/partial/availability');
//echo $this->render('application/partial/contact');
